apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: pdx-gun
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: abayomiebi/pdx-gun
          imagePullPolicy: Always
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: http
              protocol: TCP
          resources: {}
