stages:
  - build
  - test

build-jar:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "Building Jar File"
    - mvn clean install
  artifacts:
    paths:
      - pdx-gun.jar
    expire_in: 1 day

test:
  stage: test
  script:
    - echo "Testing jar file exist"
    - test -f "pdx-gun.jar"





