image: java:latest

stages:
  - build
  - database
  - docker
  - test

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "Building Jar File"
    - mvn clean install
  artifacts:
    paths:
      - pdx-gun.jar
    expire_in: 1 day


init-database:
  stage: database
  script:
    - echo "Initializing Postgres Database"
    - /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar pdx-gun.jar
  artifacts:
    paths:
      - init.sql
    expire_in: 1 day


docker-build:
  # Official docker image.
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

    # PUSH THE IMAGE TO DOCKER HUB
    - echo "${PDX_DOCKER_HUB_PWD}" | docker login -u "${PDX_DOCKER_HUB_USER}" --password-stdin

    - docker tag "${CI_REGISTRY_IMAGE}" "${PDX_DOCKER_HUB_USER}"/"${PDX_DOCKER_HUB_REPO}"
    - docker push "${PDX_DOCKER_HUB_USER}"/"${PDX_DOCKER_HUB_REPO}"
    - docker logout


