stages:
  - build

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

    # PUSH THE IMAGE TO DOCKERHUB
    - echo "${DOCKER_HUB_PWD}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin

    - docker tag "${CI_REGISTRY_IMAGE}" "${DOCKER_HUB_USER}"/"${DOCKER_HUB_REPO}"
    - docker push "${DOCKER_HUB_USER}"/"${DOCKER_HUB_REPO}"
    - docker logout
