apiVersion: v1
kind: Service
metadata:
  name: hasura
  labels:
    app: hasura
  namespace: pdx-gun
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hasura
  type: LoadBalancer
